# Generated by Django 3.2.5 on 2022-01-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('account_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabourDetails',
            fields=[
                ('fullname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('aadhar_number', models.CharField(max_length=10)),
                ('home_address', models.TextField(max_length=100)),
                ('mobile_number', models.CharField(max_length=13)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.bankaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('unit_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('unit_address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabourExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('amount', models.FloatField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.bankaccounts')),
                ('labour_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.labourdetails')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.workplace')),
            ],
        ),
    ]
